### ISSUE TITLE
media has no subscribe method error 

### ISSUE THREAD

**Issue by joshua1** [pearofducks/svelte-match-media#1]
Hi @pearofducks ,
I was trying to use this lib and got
``` 
 (in promise) Error: 'media' is not a store with a 'subscribe' method 
```
wondering why though as i see in the code that it is a derived store.

this is while using it like this 
```
if($media.mobile){...
```

**Comment by pearofducks** [comment]
Can't reproduce (see `App.svelte`) - https://github.com/pearofducks/svelte-plugin-counterrepro

Maybe you're not initializing in main.js with `setup`?

**Comment by ituxka** [comment]
I`ve faced the same issue recently, and I bet it happens because we are using sapper

**Comment by ituxka** [comment]
@pearofducks  I've added noop subscribe like so: `export let media = {subscribe: () => () => {}}` and it helped me in my sapper app

**Comment by pearofducks** [comment]
Thanks for the suggestion @ituxka - it might be because of sapper.

Unfortunately when I looked into this last, sapper had rather poor support for conditionally creating/modifying stores - but I'd gladly accept a PR that does solve this.
