### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by dkzlv** [pearofducks/svelte-match-media#10]
Hi!

Helpful library, thanks!
Now that typescript is kind of a [first class citizen in Svelte](https://github.com/sveltejs/svelte/issues/4518#issuecomment-650635007) it makes sense to add typescript definitions to the project so `svelte-check` doesn't alert you unhelpful errors like

```
Warn: Could not find a declaration file for module 'svelte-match-media'. '[...]/node_modules/svelte-match-media/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/svelte-match-media` if it exists or add a new declaration (.d.ts) file containing `declare module 'svelte-match-media';` (js)
```

Don't know what your opinion on contributions is, nor have I found a develop branch, so I don't really know how to send a PR.
I wrote the types for myself, but it would be cool if they landed in NPM some time in future. Feel free to copy and add it in `index.d.ts` file alongside `index.js`, should work out of the box.

```typescript
declare module 'svelte-match-media' {
  import { Readable } from 'svelte/store';

  export let media: Readable<{ [name: string]: boolean }>;
  export function setup(queries: { [name: string]: string }): () => void;
}
```

**Comment by pearofducks** [comment]
Thanks for the heads-up and for including the types - these are published in `1.1.0` :)
