### ISSUE TITLE
What about not using live binding export?

### ISSUE THREAD

**Issue by frederikhors** [pearofducks/svelte-match-media#11]
@pearofducks your work on this project is amazing! Thanks!

What do you think about not using [live binding export](https://github.com/pearofducks/svelte-match-media/blob/b1cafe002b43a7208f9a0cad5059ca35b163d775/index.js#L17) as [discussed here](https://github.com/rixo/rollup-plugin-svelte-hot/issues/11) because Nollup can't support it?

Is there an alternative way to do it?

Maybe we can increase performances too.

Again, thanks for all your commitment! :smile:

**Comment by pearofducks** [comment]
`1.2.0` provides `createMedia` which will avoid using the live-binding export.

There's absolutely no difference between using `createMedia` or the existing live-binding in performance. You seem to be confusing the statement from Nollup stating that supporting live-bindings would affect _their_ performance.
