### ISSUE TITLE
Bug when unsubscribing

### ISSUE THREAD

**Issue by BulatDashiev** [pearofducks/svelte-match-media#2]
https://github.com/pearofducks/svelte-match-media/blob/ad1f76deab4f5d6ac86e150039fc148777b56773/index.js#L8

needs to remove query param in usnubscribe method

**Comment by pearofducks** [comment]
Can you provide a reproduction please?

`query` here is an instance of MediaQueryList - which should always have a `removeListener` method. There's no such thing as a query param to be considered here to my knowledge.

**Comment by BulatDashiev** [comment]
the unsub method does not provide any params, hence the query parameter is undefined, you should take it from closure.

**Comment by pearofducks** [comment]
You're absolutely right, thanks for reporting this in!
