### ISSUE TITLE
Thanks and can you explain it a little bit?

### ISSUE THREAD

**Issue by frederikhors** [pearofducks/svelte-match-media#6]
Thanks a lot for your work on this!

Can you explain a little bit the code in https://github.com/pearofducks/svelte-match-media/blob/master/index.js?

Thanks again!

**Comment by pearofducks** [comment]
I'm happy to answer questions you might have, I'm not sure what to explain though.

The plugin essentially is just combining [window.matchMedia](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) and [Svelte stores](https://svelte.dev/docs#svelte_store)

**Comment by frederikhors** [comment]
What is [`setupMq()`](https://github.com/pearofducks/svelte-match-media/blob/master/index.js#L3-L9) for?

```js
const setupMq = (queryString) => (set) => {
  const query = window.matchMedia(queryString)
  const callback = (e) => set(e.matches)
  query.addListener(callback)
  callback(query)
  return () => query.removeListener(callback)
}
```

What [`setup()`](https://github.com/pearofducks/svelte-match-media/blob/master/index.js#L19-L22) does?

```js
export const setup = (queries = defaultQueries) => {
  queryStores = Object.entries(queries).reduce((acc, [mediaName, queryString]) => (acc[mediaName] = readable(false, setupMq(queryString)), acc), {})
  media = derived(Object.values(queryStores), ($queryStores) => $queryStores.reduce((acc, q, i) => (acc[Object.keys(queryStores)[i]] = q, acc), {}))
}
```

I'm newbie...

**Comment by pearofducks** [comment]
Sorry those are pretty broad/vague questions, you might be able to find someone to walk through the code with you - as it's pretty brief. I don't have time to write out an explanation like that.
