### ISSUE TITLE
 Using media queries in sapper throws `error 500` for a moment

### ISSUE THREAD

**Issue by diverent2** [pearofducks/svelte-match-media#7]
When I import `media` in a component everything remains fine.
But when I start to use an if-statement like`{#if $media.desktop}` it works, **but**
it will flash an error for a few seconds  
> 500 | Cannot read property 'subscribe' of undefined

This is a big problem: 
1. It negatively impacts performance
2. Cypress tests will fail because `error 500` is equal to "broken".

This issue also happened when I run `setup()` regardless of if I run it inside `_layout.svelte` or.
inside `client.js` or anywhere else.

You've mentioned in #5 
>  you can freely use media, **as long as you ensure media isn't null first** - since on the server it won't be initialized yet.

Maybe that's the problem here. If it is, please tell me how I could do this, I've already tried a lot but nothing seems to solve this.

**Comment by pearofducks** [comment]
Here's a quick counter-reproduction - I don't see any errors in dev or production builds.

https://github.com/pearofducks/sapper-counterrepro

If there are some errors there I'm missing then for now this plugin will have to be unsupported for use in Sapper. I do have plans to look into this in the future, but I have other projects I'm working on for now. I'm happy to accept a PR though. :)

**Comment by diverent2** [comment]
Hmm okay I also can't seem to reproduce my error outside of my specific project.

Very odd, maybe it has to do with the project size or something completely different.
At this point it could be anything and without a working repro this won't go anywhere.
I'm going to switch to an alternative solution called [svelte-media-query](https://github.com/xelaok/svelte-media-query) for now and will close this issue.
If I manage to find more information on what is going on, I will let you know and come back here.

Thanks for your time and good luck with your other projects 👍
