### ISSUE TITLE
A single listener for everything instead of a new one for each media query?

### ISSUE THREAD

**Issue by frederikhors** [pearofducks/svelte-match-media#8]
I studied your code.

Great!

I'm wondering if there is a way to only use a single listener for everything instead of a new one for each media query.

What do you think about?

I'm asking you this because this code must run on very underpowered hardware.

**Comment by pearofducks** [comment]
That's not how window.matchMedia works to my knowledge.

Multiple queries (within reason) should not tax any hardware, this sounds like premature optimization.

**Comment by frederikhors** [comment]
You are right. I said that badly.

I meant stores, why not a global one instead of a store for each media query?

**Comment by pearofducks** [comment]
Again, that's a micro-optimization. There's no way you'd see a significant performance gain from reducing N stores down to 1 (again, within reason).

If you want to address these concerns I suggest you fork the project and taylor things to your own needs.
